language: java
env:
  matrix:
# currently the only way to do a multi-dimensional env matrix
    - PLATFORM=railo40 TESTFRAMEWORK=mxunit
    - PLATFORM=railo41 TESTFRAMEWORK=mxunit
    - PLATFORM=railo42 TESTFRAMEWORK=mxunit
    - PLATFORM=lucee451 TESTFRAMEWORK=mxunit
#    - PLATFORM=acf10-linux64 TESTFRAMEWORK=mxunit
    - PLATFORM=acf902-linux64 TESTFRAMEWORK=mxunit
#    - PLATFORM=railo40 TESTFRAMEWORK=testbox
#    - PLATFORM=railo41 TESTFRAMEWORK=testbox
#    - PLATFORM=railo42 TESTFRAMEWORK=testbox
#    - PLATFORM=lucee451 TESTFRAMEWORK=testbox
#    - PLATFORM=acf10-linux64 TESTFRAMEWORK=testbox

install: ant -Dtest.framework=$TESTFRAMEWORK -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM install-ci-deps
script: ant -Dtest.framework=$TESTFRAMEWORK -Dsource=remote -Dwork.dir=$HOME/work -Dbuild.dir=$TRAVIS_BUILD_DIR -Dplatform=$PLATFORM test-ci
